ALTER TABLE RentDetails DROP FOREIGN KEY FKRentDetail463066;
ALTER TABLE RentalRecords DROP FOREIGN KEY FKRentalReco207465;
ALTER TABLE RentDetails DROP FOREIGN KEY FKRentDetail666351;
ALTER TABLE RentDetails DROP FOREIGN KEY FKRentDetail95809;
ALTER TABLE Books DROP FOREIGN KEY FKBooks441696;
DROP TABLE IF EXISTS Authors;
DROP TABLE IF EXISTS Books;
DROP TABLE IF EXISTS Librarian;
DROP TABLE IF EXISTS RentalRecords;
DROP TABLE IF EXISTS RentDetails;
DROP TABLE IF EXISTS `User`;

